# config/config.yaml
# 장치 모니터링 및 이벤트 로그 분석 설정 파일

# 기본 로깅 설정
logging:
  log_file: "logs/app.log"        # 로그 파일 경로 (프로젝트 루트 기준)
  log_level_console: "INFO"       # 콘솔 출력 레벨 (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  log_level_file: "DEBUG"         # 파일 기록 레벨
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" # 로그 포맷

# 플랫폼 설정
platform:
  is_windows: True                # 참고용 (코드 내 자동 감지)

# 이벤트 로그 분석 설정
event_log:
  log_name: "System"              # 분석할 이벤트 로그 이름
  max_events_to_read: 5000        # 최대 검색 이벤트 수
  target_sources:                 # 검색할 이벤트 소스 목록
    - "Microsoft-Windows-Kernel-PnP"
  target_event_ids:               # 검색할 이벤트 ID 목록
    - 2102
    - 219  # 장치 관련 이벤트 ID 추가 (필요 시 수정)

# LLM 분석 설정
llm:
  enabled: true                   # LLM 분석 활성화/비활성화 상태
  api_url: "https://api.x.ai/v1/chat/completions"
  model: "grok-3-mini-beta"
  check_threshold: 5              # LLM 검사 시작 이벤트 임계값
  request_timeout: 60             # API 요청 타임아웃 (초)
  temperature: 0.5
  max_log_details_for_llm: 20     # LLM에 전달할 최근 로그 수
  # LLM 응답에서 비정상으로 판단할 키워드 (소문자)
  abnormal_keywords:
    - "비정상"
    - "abnormal"
    - "반복"
    - "패턴"
    - "pattern"
    - "끊김"
    - "disconnect"
    - "오류"
    - "error"
    - "문제"
    - "issue"
    - "불안정"
    - "unstable"
    - "실패"
    - "failure"
    - "손실"
    - "loss"

# 데이터베이스 설정
database:
  path: "data/device_monitor.db"  # 데이터베이스 파일 경로
  backup_interval: 7              # 백업 주기 (일)
  retention_period: 90            # 데이터 보존 기간 (일)
  auto_cleanup: true              # 오래된 데이터 자동 정리 여부

# 보고서 설정
report:
  default_period: 7               # 기본 보고서 생성 기간 (일)
  output_dir: "reports"           # 보고서 출력 디렉토리
  formats:                        # 지원하는 보고서 포맷
    - "text"
    - "json"
    - "csv"
